# Generated by Django 4.0.4 on 2022-05-25 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studnet',
            options={'ordering': ['student_id']},
        ),
        migrations.AddField(
            model_name='studnet',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studnet',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studnet',
            name='mob',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studnet',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
