# Generated by Django 4.0.4 on 2022-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studnet', '0002_alter_studnet_options_studnet_email_studnet_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studnet',
            name='gpa',
            field=models.FloatField(),
        ),
    ]
