# Generated by Django 4.0.4 on 2022-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studnet', '0004_studnet_activation_alter_studnet_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studnet',
            name='activation',
            field=models.CharField(max_length=10),
        ),
    ]
