# Generated by Django 4.0.4 on 2022-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studnet', '0005_alter_studnet_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studnet',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
